# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 10:14
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='user_profile/', verbose_name='User Profile'),
        ),
    ]
