# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
