# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='created',
            new_name='created_at',
        ),
    ]
