# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 06:00
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161102_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='item_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='itemshot',
            field=versatileimagefield.fields.VersatileImageField(default=0, upload_to='items/', verbose_name='Item'),
            preserve_default=False,
        ),
    ]
