# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-24 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notofication_push',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
