# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 06:30
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161102_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='itemshot',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='items/', verbose_name='Item'),
        ),
    ]
