# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 08:48
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161102_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Item location'),
        ),
    ]
