# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_geometry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='geometry',
            new_name='point',
        ),
    ]
