# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-26 03:46
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161224_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='state',
            field=django_fsm.FSMField(default='new', max_length=50),
        ),
    ]
