# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-12 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161108_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='text',
            new_name='memo',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
