# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161226_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='state',
            field=django_fsm.FSMField(default='created', max_length=50, protected=True),
        ),
    ]
