# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
