# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170116_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='grade',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=True, max_length=32, null=True),
        ),
    ]
