# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-24 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170121_1544'),
        ('core', '0014_auto_20170124_1331'),
    ]

    operations = [
    ]
