# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
