# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 08:46
from __future__ import unicode_literals

from django.db import migrations
from core.models import User


def addFacebookScraperUser(apps, schema_editor):
    User.objects.create(username="Facebook")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170216_1640'),
    ]

    operations = [
        migrations.RunPython(addFacebookScraperUser),
    ]
