# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170216_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
