# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-14 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'scraper', '0001_initial'), (b'scraper', '0002_auto_20170214_1645')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=64, unique=True)),
                ('from_id', models.CharField(blank=True, max_length=64, null=True)),
                ('from_name', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('item_type', models.CharField(blank=True, max_length=16, null=True)),
                ('link', models.CharField(blank=True, max_length=512, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
