# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-14 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial_squashed_0002_auto_20170214_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fb_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
